name: deploy-cloudflare-worker

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: deploy-cloudflare-worker-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun
      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: 7.1

      - name: Restore cached responses
        uses: actions/cache/restore@v5
        with:
          path: .bestdori-cache
          key: bestdori-${{ github.run_id }}
          restore-keys: bestdori-

      - name: Clean old responses
        run: find .bestdori-cache -type f -mtime +28 -print -delete

      - name: Build site
        run: bun run build
        env:
          GOATCOUNTER_ENDPOINT: ${{ vars.GOATCOUNTER_ENDPOINT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload site build artifact
        uses: actions/upload-artifact@v7
        with:
          name: site
          include-hidden-files: true
          path: site/dist/

      - name: Save response cache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: .bestdori-cache
          key: bestdori-${{ github.run_id }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-worker/${{ github.ref_name }}
      url: ${{ steps.deploy-cloudflare-worker.outputs.deployment-url }}

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-bun

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: site
          path: site/dist/

      - name: Deploy to Cloudflare Workers
        id: deploy-cloudflare-worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: ${{ github.ref == 'refs/heads/main' && 'deploy' || 'versions upload' }}
          workingDirectory: site/
          secrets: |
            UPSTASH_REDIS_REST_URL
            UPSTASH_REDIS_REST_TOKEN
            GEMINI_API_KEY
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
