name: deploy

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-bun
      - uses: AnimMouse/setup-ffmpeg@v1.2.3
        with:
          version: 7.1

      - name: Restore cached responses
        uses: actions/cache/restore@v6.1.0
        with:
          path: .bestdori-cache
          key: bestdori-${{ github.run_id }}
          restore-keys: bestdori-

      - name: Clean old responses
        run: find .bestdori-cache -type f -mtime +84 -print -delete

      - name: Build site
        run: bun run build
        env:
          UMAMI_SITE_ID: ${{ vars.UMAMI_SITE_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload site build artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: site
          include-hidden-files: true
          path: |
            site/dist/
            site/.wrangler/

      - name: Upload generated data.js
        uses: actions/upload-artifact@v7.0.1
        if: always()
        with:
          name: data
          path: packages/bestdori/src/data.js
          if-no-files-found: ignore

      - name: Upload all text artifacts cache
        uses: actions/upload-artifact@v7.0.1
        if: always()
        with:
          name: text-cache
          include-hidden-files: true
          path: |
            .bestdori-cache/*.json
            .bestdori-cache/*.txt
          if-no-files-found: ignore

      - name: Save response cache
        uses: actions/cache/save@v6.1.0
        if: always()
        with:
          path: .bestdori-cache
          key: bestdori-${{ github.run_id }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: ./.github/actions/setup-bun
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.15.0

      - name: Download build artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: site
          path: site

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: site/
          secrets: |
            UPSTASH_REDIS_REST_URL
            UPSTASH_REDIS_REST_TOKEN
            GEMINI_API_KEY
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
